// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/titan.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_api_proto_titan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_titan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_titan_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_api_proto_titan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_titan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_titan_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_api_proto_titan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_titan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_titan_proto_rawDescGZIP(), []int{2}
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_api_proto_titan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_titan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_titan_proto_rawDescGZIP(), []int{3}
}

func (x *PollResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PollResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PollResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_api_proto_titan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_titan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_titan_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_api_proto_titan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_titan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_titan_proto_rawDescGZIP(), []int{5}
}

var File_api_proto_titan_proto protoreflect.FileDescriptor

const file_api_proto_titan_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/titan.proto\x12\x05titan\">\n" +
	"\x0eEnqueueRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"!\n" +
	"\x0fEnqueueResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\r\n" +
	"\vPollRequest\"L\n" +
	"\fPollResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x1c\n" +
	"\n" +
	"AckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\r\n" +
	"\vAckResponse2\xa0\x01\n" +
	"\x05Titan\x128\n" +
	"\aEnqueue\x12\x15.titan.EnqueueRequest\x1a\x16.titan.EnqueueResponse\x12/\n" +
	"\x04Poll\x12\x12.titan.PollRequest\x1a\x13.titan.PollResponse\x12,\n" +
	"\x03Ack\x12\x11.titan.AckRequest\x1a\x12.titan.AckResponseB'Z%github.com/kmranimesh/titan/api/protob\x06proto3"

var (
	file_api_proto_titan_proto_rawDescOnce sync.Once
	file_api_proto_titan_proto_rawDescData []byte
)

func file_api_proto_titan_proto_rawDescGZIP() []byte {
	file_api_proto_titan_proto_rawDescOnce.Do(func() {
		file_api_proto_titan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_titan_proto_rawDesc), len(file_api_proto_titan_proto_rawDesc)))
	})
	return file_api_proto_titan_proto_rawDescData
}

var file_api_proto_titan_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_titan_proto_goTypes = []any{
	(*EnqueueRequest)(nil),  // 0: titan.EnqueueRequest
	(*EnqueueResponse)(nil), // 1: titan.EnqueueResponse
	(*PollRequest)(nil),     // 2: titan.PollRequest
	(*PollResponse)(nil),    // 3: titan.PollResponse
	(*AckRequest)(nil),      // 4: titan.AckRequest
	(*AckResponse)(nil),     // 5: titan.AckResponse
}
var file_api_proto_titan_proto_depIdxs = []int32{
	0, // 0: titan.Titan.Enqueue:input_type -> titan.EnqueueRequest
	2, // 1: titan.Titan.Poll:input_type -> titan.PollRequest
	4, // 2: titan.Titan.Ack:input_type -> titan.AckRequest
	1, // 3: titan.Titan.Enqueue:output_type -> titan.EnqueueResponse
	3, // 4: titan.Titan.Poll:output_type -> titan.PollResponse
	5, // 5: titan.Titan.Ack:output_type -> titan.AckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_titan_proto_init() }
func file_api_proto_titan_proto_init() {
	if File_api_proto_titan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_titan_proto_rawDesc), len(file_api_proto_titan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_titan_proto_goTypes,
		DependencyIndexes: file_api_proto_titan_proto_depIdxs,
		MessageInfos:      file_api_proto_titan_proto_msgTypes,
	}.Build()
	File_api_proto_titan_proto = out.File
	file_api_proto_titan_proto_goTypes = nil
	file_api_proto_titan_proto_depIdxs = nil
}
