// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/titan.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Titan_Enqueue_FullMethodName = "/titan.Titan/Enqueue"
	Titan_Poll_FullMethodName    = "/titan.Titan/Poll"
	Titan_Ack_FullMethodName     = "/titan.Titan/Ack"
)

// TitanClient is the client API for Titan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TitanClient interface {
	// Enqueue accepts a new task
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	// Poll retrieves a task from the queue
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
	// Ack marks a task as completed
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
}

type titanClient struct {
	cc grpc.ClientConnInterface
}

func NewTitanClient(cc grpc.ClientConnInterface) TitanClient {
	return &titanClient{cc}
}

func (c *titanClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, Titan_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titanClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, Titan_Poll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titanClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Titan_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TitanServer is the server API for Titan service.
// All implementations must embed UnimplementedTitanServer
// for forward compatibility.
type TitanServer interface {
	// Enqueue accepts a new task
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	// Poll retrieves a task from the queue
	Poll(context.Context, *PollRequest) (*PollResponse, error)
	// Ack marks a task as completed
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	mustEmbedUnimplementedTitanServer()
}

// UnimplementedTitanServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTitanServer struct{}

func (UnimplementedTitanServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedTitanServer) Poll(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedTitanServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedTitanServer) mustEmbedUnimplementedTitanServer() {}
func (UnimplementedTitanServer) testEmbeddedByValue()               {}

// UnsafeTitanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TitanServer will
// result in compilation errors.
type UnsafeTitanServer interface {
	mustEmbedUnimplementedTitanServer()
}

func RegisterTitanServer(s grpc.ServiceRegistrar, srv TitanServer) {
	// If the following call panics, it indicates UnimplementedTitanServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Titan_ServiceDesc, srv)
}

func _Titan_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Titan_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Titan_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Titan_Poll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanServer).Poll(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Titan_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Titan_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Titan_ServiceDesc is the grpc.ServiceDesc for Titan service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Titan_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "titan.Titan",
	HandlerType: (*TitanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _Titan_Enqueue_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _Titan_Poll_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _Titan_Ack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/titan.proto",
}
